spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:dev}
      username: ${MONGODB_USERNAME:developer}
      password: ${MONGODB_PASSWORD:local}
