spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:demo}
      username: ${MONGODB_USERNAME:user}
      password: ${MONGODB_PASSWORD:password}
